# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Stefan de Lange <langestefan@msn.com>
CodeOfConductContact: langestefan@msn.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Stefan de Lange
MarkdownIndentation: 2
PackageName: SolarPosition
PackageOwner: PVSMC
PackageUUID: 7479b45c-9729-5219-acaa-214f6cdedf5b
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
